name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instala as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Executa os testes de API
      - name: Run Playwright Tests
        run: npx playwright test

      # Commit e push do relatório gerado para a branch main
      - name: Commit and Push Report
        run: |
          git config --global user.email "erik.fernandes87@gmail.com"  # E-mail configurado
          git config --global user.name "Erik"                         # Nome configurado
          git add playwright-report
          git commit -m "Adiciona relatório HTML"
          git push origin main
